table Date
	lineageTag: 08015f70-7d70-4eda-80f2-1a924d8de049

	measure MaxDate = max('Date'[Date])
		formatString: General Date
		lineageTag: 0976e05e-8244-4206-873e-bf06dafd798a

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="6153" Group="GeneralDateTimeLong" FormatString="G" /></DateTimes></Format>

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 452d8412-eb71-4501-b1ec-22a6d8f7b4fc
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = DateKey

		annotation PBI_WasHiddenAtRefresh = False

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: b59962cf-9e73-4b25-81a6-a8cd96acb85c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="DateTimeCustom"><DateTimes><DateTime LCID="6153" Group="ShortDate" FormatString="dd/MM/yyyy" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####Date

		annotation PBI_NameAtRefresh = Date

		annotation PBI_WasHiddenAtRefresh = False

		annotation UnderlyingDateTimeDataType = Date

	column Month
		dataType: string
		lineageTag: 4750fc03-4a03-4e81-ad2f-5a7ff70795e9
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month No'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Month

		annotation PBI_WasHiddenAtRefresh = False

	column 'Month No'
		dataType: int64
		formatString: 0
		lineageTag: 342d793c-e59b-4422-a2d4-9cd21bcf71b1
		summarizeBy: none
		sourceColumn: Month No

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Month No

		annotation PBI_WasHiddenAtRefresh = False

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 44a0cfa6-e2e7-4d97-87f3-16e865bff990
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Fiscal Year

		annotation PBI_WasHiddenAtRefresh = False

	column 'Fiscal Quarter'
		dataType: int64
		formatString: 0
		lineageTag: 7602a0cf-209b-43e6-b990-596acf4e5840
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Fiscal Quarter

		annotation PBI_WasHiddenAtRefresh = False

	column 'Fiscal Period No'
		dataType: int64
		formatString: 0
		lineageTag: 20cea2de-faaf-4576-95d8-4aa5c6711c98
		summarizeBy: none
		sourceColumn: Fiscal Period No

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Fiscal Period No

		annotation PBI_WasHiddenAtRefresh = False

	column 'Fiscal Period'
		dataType: string
		lineageTag: ef63f918-fa35-43ba-ad08-554aafc929e1
		summarizeBy: none
		sourceColumn: Fiscal Period
		sortByColumn: 'Fiscal Period No'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Fiscal Period

		annotation PBI_WasHiddenAtRefresh = False

	hierarchy 'Fiscal Calendar'
		lineageTag: 0cebbf4f-339a-4006-9011-5e5b75865558

		level Year
			lineageTag: a6db7dcb-1ddd-409d-ab48-49a504f71c62
			column: 'Fiscal Year'

		level 'Fiscal Period'
			lineageTag: b8ba6dfc-be04-4f62-b15c-1f8dfc511a8a
			column: 'Fiscal Period'

	partition Date-09ab7aeb-ed6f-4f1a-ae77-5e5a9261c99b = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    Source=    Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT *#(lf), FiscalYear * 100  + MonthNumberOfYear as FiscalPeriodNo#(lf), CONVERT (varchar(4), FiscalYear) + '-' + format(MonthNumberOfYear,'00') as FiscalPeriod#(lf)FROM DimDate"]),
				     #"Renamed Columns" = Table.RenameColumns(Source,{{"FullDateAlternateKey", "Date"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CalendarQuarter", "CalendarSemester", "CalendarYear", "DayNumberOfMonth", "DayNumberOfWeek", "DayNumberOfYear", "EnglishDayNameOfWeek"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"EnglishMonthName", "MonthOfYear"}, {"FiscalQuarter", "Fiscal Quarter"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"FiscalSemester"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"FiscalYear", "Fiscal Year"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns2",{"FrenchMonthName", "FrenchDayNameOfWeek", "SpanishDayNameOfWeek", "SpanishMonthName", "WeekNumberOfYear"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns2",{{"MonthOfYear", "Month"}, {"MonthNumberOfYear", "Month No"}, {"FiscalPeriod", "Fiscal Period"}, {"FiscalPeriodNo", "Fiscal Period No"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns3",{{"DateKey", Int64.Type}, {"Date", type date}, {"Month No", Int64.Type}, {"Fiscal Quarter", Int64.Type}, {"Fiscal Year", Int64.Type}, {"Fiscal Period No", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_DescriptionAtRefresh

