table Department
	lineageTag: 5336f1dc-c705-4e46-b65d-20ae702fa13c

	column DepartmentGroupKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 76789a93-3b7a-4ff5-87d4-96546a37f2b9
		summarizeBy: none
		sourceColumn: DepartmentGroupKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = DepartmentGroupKey

		annotation PBI_WasHiddenAtRefresh = False

	column ParentDepartmentGroupKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 19cfe0cd-f4d3-45a7-a957-cc6376de79cb
		summarizeBy: none
		sourceColumn: ParentDepartmentGroupKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ParentDepartmentGroupKey

		annotation PBI_WasHiddenAtRefresh = False

	column 'Department Name'
		dataType: string
		lineageTag: 8c0e2658-55bd-488f-adc2-1e06876321ef
		summarizeBy: none
		sourceColumn: Department Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Department Name

		annotation PBI_WasHiddenAtRefresh = False

	column DepartmentPath = path('Department'[DepartmentGroupKey], 'Department'[ParentDepartmentGroupKey])
		lineageTag: 2570319f-496c-49ab-a375-e2d905975b21
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column 'Department Group' = LOOKUPVALUE( Department[Department Name], Department[DepartmentGroupKey]  ,   PATHITEM( Department[DepartmentPath], 1,INTEGER))
		lineageTag: 24725754-6b0e-4436-81ac-90080ee6864e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column Department = LOOKUPVALUE( Department[Department Name], Department[DepartmentGroupKey]  ,   PATHITEM( Department[DepartmentPath], 2,INTEGER))
		lineageTag: 901ab0e1-0234-49af-b861-a45b87cc3a99
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	hierarchy 'Department Hierarchy'
		lineageTag: 05b27f4f-d151-4092-8ea8-223b275457ba

		level 'Department Group'
			lineageTag: 1ced408b-cb11-4f23-b008-33a90268cdf0
			column: 'Department Group'

		level 'Sub Department'
			lineageTag: c4748ae0-9f36-416c-ad2a-c7c137e91504
			column: Department

	partition Department-d6337107-b576-462b-b572-d473a86f9f30 = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    dbo_DimDepartmentGroup = Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT * FROM DimDepartmentGroup"]),
				    #"Renamed Columns" = Table.RenameColumns(dbo_DimDepartmentGroup,{{"DepartmentGroupName", "Department Name"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"DepartmentGroupKey", Int64.Type}, {"ParentDepartmentGroupKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = Department

	annotation PBI_DescriptionAtRefresh

