table 'Finanical Report'
	lineageTag: 72e0a53f-b8c6-4286-bab3-c9a312b79207

	measure ReportScope =
			
			IF (
			    OR (
			        HASONEVALUE ( 'Finanical Report'[Report Heading] ) = FALSE (),
			        OR (
			            ISINSCOPE ( 'Finanical Report'[Report Section] ) = FALSE (),
			            CALCULATE (
			                DISTINCTCOUNT ( 'Finanical Report'[Report No] ),
			                ALLEXCEPT (
			                    'Finanical Report',
			                    'Finanical Report'[Report Heading],
			                    'Finanical Report'[Report]
			                )
			            ) > 1
			        )
			    ),
			    1
			)
		formatString: 0
		lineageTag: 516b0d04-fb5b-4017-a4b7-2a03046365a0

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure 'LineNo Count' = COUNTROWS('Finanical Report')
		formatString: 0
		lineageTag: ad151df9-532a-42ae-ad72-b8d2e3fd665e

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	column Operator
		dataType: string
		lineageTag: a90dfdb3-1f0f-430a-a36c-84fbbbbaf0d4
		summarizeBy: none
		sourceColumn: Operator

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Operator

		annotation PBI_WasHiddenAtRefresh = False

	column Calc1
		dataType: string
		isHidden
		lineageTag: f87f61ef-ba40-47e6-a5ed-0f07e870c741
		summarizeBy: none
		sourceColumn: Calc1

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Calc1

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report No'
		dataType: int64
		formatString: 0
		lineageTag: 2c0f0472-1a70-4b87-b964-7bf3b634e3c3
		summarizeBy: none
		sourceColumn: Report No

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = Report No

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Section'
		dataType: string
		lineageTag: e9713b72-e747-4b2c-9ffb-b91c5daa4217
		summarizeBy: none
		sourceColumn: Report Section
		sortByColumn: 'Report No'

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Section

		annotation PBI_WasHiddenAtRefresh = False

	column 'Report Heading'
		dataType: string
		lineageTag: 239213fb-32a2-4bb2-94ca-09b5f42ed6e2
		summarizeBy: none
		sourceColumn: Report Heading
		sortByColumn: ReportHeadingNo

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report Heading

		annotation PBI_WasHiddenAtRefresh = False

	column Report
		dataType: string
		lineageTag: 6e0af1aa-ce2b-4ea6-8889-1dfecf6761af
		summarizeBy: none
		sourceColumn: Report

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Report

		annotation PBI_WasHiddenAtRefresh = False

	column ReportHeadingNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 330e53e8-583f-40ea-93ac-b786d526ac50
		summarizeBy: none
		sourceColumn: ReportHeadingNo

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ReportHeadingNo

		annotation PBI_WasHiddenAtRefresh = False

	column LineNo
		dataType: int64
		formatString: 0
		lineageTag: efadddf0-e979-4e1f-9428-53a3cdd5482d
		summarizeBy: none
		sourceColumn: LineNo

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = LineNo

		annotation PBI_WasHiddenAtRefresh = False

	column LinkReport
		dataType: string
		lineageTag: c19e21d1-dede-4994-968c-9b942c9b60af
		summarizeBy: none
		sourceColumn: LinkReport

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = LinkReport

		annotation PBI_WasHiddenAtRefresh = False

	column LinkLineNo
		dataType: int64
		formatString: 0
		lineageTag: f17e472b-82d5-4aa9-a31f-0a79e531a00b
		summarizeBy: none
		sourceColumn: LinkLineNo

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = LinkLineNo

		annotation PBI_WasHiddenAtRefresh = False

	column LinkSignage
		dataType: double
		lineageTag: faee3782-6c06-4a79-a107-67445c4dbb41
		summarizeBy: none
		sourceColumn: LinkSignage

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = LinkSignage

		annotation PBI_WasHiddenAtRefresh = False

	column LinkHeading
		dataType: string
		lineageTag: 54e183e1-7f47-4ba0-9f7b-aa3caaa47c4f
		summarizeBy: none
		sourceColumn: LinkHeading

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = LinkHeading

		annotation PBI_WasHiddenAtRefresh = False

	hierarchy 'Report Hierarchy'
		lineageTag: 5bf225af-7e89-4a53-9869-d612c907e091

		level 'Report Heading'
			lineageTag: 71014ec0-7d0b-4577-9ca4-def7eabb656b
			column: 'Report Heading'

		level 'Report Section'
			lineageTag: 9845091e-246a-4008-be66-586641688e6b
			column: 'Report Section'

	partition 'Finanical Report-63ad57e2-cdef-404b-868c-19112537ee5b' = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    Source=   Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT * FROM staging.AccountRange"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"ReportNo", "Report No"}, {"ReportHeading", "Report Heading"}, {"ReportSection", "Report Section"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Report No", Int64.Type}, {"ReportHeadingNo", Int64.Type}, {"LineNo", Int64.Type}, {"LinkLineNo", Int64.Type}, {"LinkSignage", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,1,Replacer.ReplaceValue,{"LinkSignage"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = Finanical Report

	annotation PBI_DescriptionAtRefresh

