table 'General Ledger'
	lineageTag: 237cb2fe-e169-45cc-bd44-03ccb6304898

	measure 'GL Amount' = VAR s =   SELECTEDVALUE(Scenario[Scenario],"Actual") RETURN   CALCULATE(sum('General Ledger'[BaseAmount] ), Scenario[Scenario] =s) * 'Finanical Report'[ReportScope]
		formatString: #,0
		lineageTag: 38e3580e-4e18-486b-aa59-f6f688a73558

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'GL Budget' = VAR s =   SELECTEDVALUE(Scenario[Scenario],"Budget") RETURN   CALCULATE(sum('General Ledger'[BaseAmount] ), Scenario[Scenario] =s) * 'Finanical Report'[ReportScope]
		formatString: #,0
		lineageTag: 5b5cbaa1-da3f-4655-8828-7d39af75ec55

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'GL Variance' = [GL Amount] -[GL Budget]
		formatString: #,0
		lineageTag: 8d8acf0c-b2e7-4495-b34b-5a542341476e

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'GL Variance%' = DIVIDE([GL Variance] ,[GL Budget])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f2ff6259-2b0d-4020-88ab-c82d47c935f2

		annotation Format = <Format Format="Percentage" Accuracy="1" />

	measure 'Base Amount' = sum('General Ledger'[BaseAmount])
		isHidden
		lineageTag: 2b2699b8-41d4-414e-b7fb-47362e26483f

		annotation Format = <Format Format="General" />

	measure 'GL Opening Balance' = var MaxPeriod =MIN('Date'[Fiscal Period No] ) RETURN CALCULATE( [GL Amount] , all('Date'), 'Date'[Fiscal Period No] < MaxPeriod)
		formatString: #,0
		lineageTag: 41b2a836-a92b-4c98-b64a-c96161ccab12

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'GL Closing Balance' = var MaxPeriod =max('Date'[Fiscal Period No] ) RETURN CALCULATE( [GL Amount] , all('Date'), 'Date'[Fiscal Period No] <= MaxPeriod)
		formatString: #,0
		lineageTag: 87bf7b0c-93b8-4058-b83e-665c595b53c3

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'GL Movement' = ```
			[GL Amount] 
			```
		formatString: #,0
		lineageTag: 2029804e-0c9f-497a-80e6-b1e5cdde63d5

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure 'CashFlow Amount' = SWITCH(SELECTEDVALUE('Finanical Report'[Operator]), "DaxSubTotal", [DaxSubTotal] , "Reconciliation",[Reconciliation],[CashFlow Base]) * 'Finanical Report'[ReportScope]
		formatString: #,0
		lineageTag: 2715700b-e1c8-42f7-9284-a7503e365c63

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure LinkAmount =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        IF ( LEFT ( r, 2 ) = "BS",   [GL Movement], [GL Amount] ),
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[LinkSignage])
		formatString: #,0
		displayFolder: _Internal
		lineageTag: c4e25950-c995-431d-b825-61e1a5ad3f7c

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure LinkGroup =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkHeading] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        IF ( LEFT ( r, 2 ) = "BS", [GL Movement], [GL Amount] ),
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LinkHeading],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[Report Heading] = l,
			        'Finanical Report'[Report] = r
			    )* max('Finanical Report'[LinkSignage])
		formatString: #,0
		displayFolder: _Internal
		lineageTag: 1db4e718-cd7e-4382-bc72-dd638b40aefa

		annotation Format = <Format Format="NumberDecimal" Accuracy="0" ThousandSeparator="True" />

	measure DaxSubTotal = CALCULATE(  SUMX(values ('Finanical Report'[LineNo]),   [CashFlow Base] ), ALLEXCEPT('Finanical Report', 'Finanical Report'[ReportHeadingNo] , 'Finanical Report'[Report]))
		formatString: 0
		displayFolder: _Internal
		lineageTag: 005e92db-3e36-4c1a-a6b7-327195e7fe9b

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure DaxRunningSum = ```
			VAR l=SELECTEDVALUE('Finanical Report'[LineNo]) RETURN CALCULATE( SUMX(VALUES('Finanical Report'[LineNo]),  [LinkAmount]+ [LinkGroup]) , ALLEXCEPT('Finanical Report', 'Finanical Report'[Report]), 'Finanical Report'[LineNo] < l, 'Finanical Report'[Operator]  <> "DaxRunningSum" , 'Finanical Report'[Operator] <> "OpeningBalance") 
			```
		formatString: 0
		displayFolder: _Internal
		lineageTag: fc719e72-4b21-47c3-9c67-675ef5e3cb60

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure LinkOpenBalance =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        [GL Opening Balance],
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[LinkSignage])
		formatString: 0
		displayFolder: _Internal
		lineageTag: f699e5a1-a1bf-4a9b-b251-af091be22a6a

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure LinkClosingBalance =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        [GL Closing Balance],
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[LinkSignage])
		formatString: "€"#,0.###############;-"€"#,0.###############;"€"#,0.###############
		displayFolder: _Internal
		lineageTag: d1ffb3a4-5500-4c1b-a3fe-96802ac14a67

		annotation Format = <Format Format="CurrencyGeneral" ThousandSeparator="True"><Currency LCID="6153" DisplayName="€ English (Ireland)" Symbol="€" PositivePattern="0" NegativePattern="1" /></Format>

	measure 'CashFlow Base' = SWITCH(SELECTEDVALUE('Finanical Report'[Operator]),"Link", [LinkAmount],  "OpeningBalance", [LinkOpenBalance], "ClosingBalance", [LinkClosingBalance], "LinkGroup", [LinkGroup]  , "DaxRunningSum",[DaxRunningSum]  )  * 'Finanical Report'[ReportScope]
		formatString: 0
		displayFolder: _Internal
		lineageTag: 4b97d575-2d5d-4922-9f25-cf3541dc7c02

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	measure Reconciliation = CALCULATE( [DaxRunningSum], ALLEXCEPT('Finanical Report', 'Finanical Report'[Report]),  'Finanical Report'[LineNo]=19)  + CALCULATE([GL Opening Balance] , all('Finanical Report'), 'Finanical Report'[Report Section] ="Cash")  - CALCULATE([GL Closing Balance] , all('Finanical Report'), 'Finanical Report'[Report Section] ="Cash")
		formatString: 0
		lineageTag: 855c177c-7bd5-4fcd-addd-80fd400009ce

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 98f96fe9-728e-4c09-9ac3-dabe69a7f796
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = DateKey

		annotation PBI_WasHiddenAtRefresh = False

	column OrganizationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c194de1-7534-4706-9d36-cda2ddf91979
		summarizeBy: none
		sourceColumn: OrganizationKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = OrganizationKey

		annotation PBI_WasHiddenAtRefresh = False

	column FinanceKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a9e3579e-8ffd-41df-aaf2-b49dea735b27
		summarizeBy: count
		sourceColumn: FinanceKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = FinanceKey

		annotation PBI_WasHiddenAtRefresh = False

	column DepartmentGroupKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a4be9d1c-f002-430e-b38d-c8e1bfd9fab1
		summarizeBy: none
		sourceColumn: DepartmentGroupKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = DepartmentGroupKey

		annotation PBI_WasHiddenAtRefresh = False

	column ScenarioKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6e2730af-a4f6-4c4c-a05a-a200d40cff00
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ScenarioKey

		annotation PBI_WasHiddenAtRefresh = False

	column AccountKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ecbf2a4c-b24c-4bc3-8e9c-39636525c1fc
		summarizeBy: none
		sourceColumn: AccountKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = AccountKey

		annotation PBI_WasHiddenAtRefresh = False

	column Date
		dataType: dateTime
		isHidden
		formatString: dddd d mmmm yyyy
		lineageTag: d5802c42-3fa9-41d7-b42a-c651cb47794d
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation Format = <Format Format="DateTimeGeneralPattern"><DateTimes><DateTime LCID="6153" Group="LongDate" FormatString="dddd d MMMM yyyy" /></DateTimes></Format>

		annotation DataTypeAtRefresh = DateTime#####Date

		annotation PBI_NameAtRefresh = Date

		annotation PBI_WasHiddenAtRefresh = False

	column 'Account Type'
		dataType: string
		isHidden
		lineageTag: eb06d4a5-c607-4b14-a0a3-7e2f4cbc0b67
		summarizeBy: none
		sourceColumn: Account Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Account Type

		annotation PBI_WasHiddenAtRefresh = False

	column BaseAmount
		dataType: decimal
		isHidden
		formatString: "€"#,0.###############;-"€"#,0.###############;"€"#,0.###############
		lineageTag: 87078bb8-3510-4993-9e23-d23ac6e123ec
		summarizeBy: none
		sourceColumn: BaseAmount

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="CurrencyGeneral" ThousandSeparator="True"><Currency LCID="6153" DisplayName="€ English (Ireland)" Symbol="€" PositivePattern="0" NegativePattern="1" /></Format>

		annotation DataTypeAtRefresh = Decimal#####not a type

		annotation PBI_NameAtRefresh = BaseAmount

		annotation PBI_WasHiddenAtRefresh = False

	partition 'General Ledger-d699db49-9681-49fc-b81e-bf1140f35c13' = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    Source = Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT * FROM FactFinance"]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FinanceKey", Int64.Type}, {"DateKey", Int64.Type}, {"OrganizationKey", Int64.Type}, {"DepartmentGroupKey", Int64.Type}, {"ScenarioKey", Int64.Type}, {"AccountKey", Int64.Type}, {"Amount", type number}, {"Date", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Date", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"AccountKey"}, Account, {"AccountKey"}, "Account", JoinKind.Inner),
				    #"Expanded Account1" = Table.ExpandTableColumn(#"Merged Queries", "Account", {"Account Type"}, {"Account Type"}),
				    #"Apply Operator (+/-)" = Table.AddColumn(#"Expanded Account1", "BaseAmount", each ([Amount]  * (if [Account Type]="Expenditures" or [Account Type]="Liabilities" then -1 else 1 ))),
				    #"Removed Columns" = Table.RemoveColumns(#"Apply Operator (+/-)",{"Amount"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"BaseAmount", Currency.Type}})
				in
				    #"Changed Type2"

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = General Ledger

	annotation PBI_DescriptionAtRefresh

