table Organization
	lineageTag: eaf5762c-b329-436a-b7c9-556fcc598f81

	column OrganizationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: df6f19b0-997c-4f1f-a692-970de951f469
		summarizeBy: none
		sourceColumn: OrganizationKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = OrganizationKey

		annotation PBI_WasHiddenAtRefresh = False

	column ParentOrganizationKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: edc862bf-9661-4cf0-afff-a726fe2b54a7
		summarizeBy: none
		sourceColumn: ParentOrganizationKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ParentOrganizationKey

		annotation PBI_WasHiddenAtRefresh = False

	column PercentageOfOwnership
		dataType: double
		isHidden
		lineageTag: db526a92-5be8-45db-9c21-2c8f86a4fc03
		summarizeBy: none
		sourceColumn: PercentageOfOwnership

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="General" />

		annotation DataTypeAtRefresh = Double#####not a type

		annotation PBI_NameAtRefresh = PercentageOfOwnership

		annotation PBI_WasHiddenAtRefresh = False

	column 'Organization Name'
		dataType: string
		lineageTag: 5e313b8a-36ae-4575-96c8-f56730564f7c
		summarizeBy: none
		sourceColumn: Organization Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Organization Name

		annotation PBI_WasHiddenAtRefresh = False

	column CurrencyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f73a8fcb-ccc7-4c08-9454-92ab6121f0a6
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = CurrencyKey

		annotation PBI_WasHiddenAtRefresh = False

	column OrganizationPath = path(Organization[OrganizationKey], Organization[ParentOrganizationKey])
		isHidden
		lineageTag: c162a6c0-717a-4777-ace3-fe88cebc14d4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column 'Organization Path Length' = PATHLENGTH( Organization[OrganizationPath] )
		formatString: 0
		lineageTag: 59c39cef-6c29-484b-ba60-524277d6155b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

	column Company = LOOKUPVALUE( Organization[Organization Name], Organization[OrganizationKey]   ,   PATHITEM( Organization[OrganizationPath], 1,INTEGER))
		lineageTag: 3d539da1-fd76-4047-8fbf-e0a0b933a9c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column Region = LOOKUPVALUE( Organization[Organization Name], Organization[OrganizationKey]   ,   PATHITEM( Organization[OrganizationPath], 2,INTEGER))
		lineageTag: f38313da-c376-49ad-a791-607487d8fb43
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column Country = LOOKUPVALUE( Organization[Organization Name], Organization[OrganizationKey]   ,   PATHITEM( Organization[OrganizationPath], 3,INTEGER))
		lineageTag: d1dcc9bb-75dd-4ac9-bc79-6bdea18f6961
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	column 'Organization L4' = LOOKUPVALUE( Organization[Organization Name], Organization[OrganizationKey]   ,   PATHITEM( Organization[OrganizationPath], 4,INTEGER))
		lineageTag: 752a3add-adfa-48f4-9de0-81f06efba8ba
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

	hierarchy Organization
		lineageTag: f79e21b4-4478-40af-b8b6-75b9ac8c1524

		level Company
			lineageTag: bc5a03bf-6f9f-4877-b56b-0004e007baca
			column: Company

		level Region
			lineageTag: a0fae26d-8fcb-4c28-b5ab-0dcdac0d800e
			column: Region

		level Country
			lineageTag: a38b9d6e-c9a2-4fe2-8a81-a9246c7831e2
			column: Country

		level Division
			lineageTag: 7c16125a-7038-47cc-9716-f898c3d769e3
			column: 'Organization L4'

	partition Organization-d9ef92dd-2885-427f-bb6c-29b8742818b8 = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    dbo_DimOrganization=  Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT * FROM DimOrganization"]),
				    #"Renamed Columns" = Table.RenameColumns(dbo_DimOrganization,{{"OrganizationName", "Organization Name"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"OrganizationKey", Int64.Type}, {"ParentOrganizationKey", Int64.Type}, {"PercentageOfOwnership", type number}, {"CurrencyKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_DescriptionAtRefresh

