table Scenario
	lineageTag: aa55d8a1-9a57-4815-8fe3-48acd590fb88

	column ScenarioKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f23aa67a-f3b8-48a0-b7b0-2957a5a9e16f
		summarizeBy: none
		sourceColumn: ScenarioKey

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation DataTypeAtRefresh = Int64#####not a type

		annotation PBI_NameAtRefresh = ScenarioKey

		annotation PBI_WasHiddenAtRefresh = False

	column Scenario
		dataType: string
		lineageTag: 903301f0-ed8c-4634-a39a-32155e767b39
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation DataTypeAtRefresh = String#####not a type

		annotation PBI_NameAtRefresh = Scenario

		annotation PBI_WasHiddenAtRefresh = False

	partition Scenario-180ddbc1-ecb6-47cf-a0a3-a068bda0bc9c = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    dbo_DimScenario = Sql.Database("prd-sql.roebuck.local", "adventureworksdw", [Query="SELECT * FROM DimScenario"]),
				    #"Renamed Columns" = Table.RenameColumns(dbo_DimScenario,{{"ScenarioName", "Scenario"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"ScenarioKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_DescriptionAtRefresh

