CREATE TABLE [dbo].[Date] (

	[DateID] int NOT NULL, 
	[Date] datetime2(6) NULL, 
	[DateBKey] char(10) NULL, 
	[DayOfMonth] varchar(2) NULL, 
	[DaySuffix] varchar(4) NULL, 
	[DayName] varchar(9) NULL, 
	[DayOfWeek] char(1) NULL, 
	[DayOfWeekInMonth] varchar(2) NULL, 
	[DayOfWeekInYear] varchar(2) NULL, 
	[DayOfQuarter] varchar(3) NULL, 
	[DayOfYear] varchar(3) NULL, 
	[WeekOfMonth] varchar(1) NULL, 
	[WeekOfQuarter] varchar(2) NULL, 
	[WeekOfYear] varchar(2) NULL, 
	[Month] varchar(2) NULL, 
	[MonthName] varchar(9) NULL, 
	[MonthOfQuarter] varchar(2) NULL, 
	[Quarter] char(1) NULL, 
	[QuarterName] varchar(9) NULL, 
	[Year] char(4) NULL, 
	[YearName] char(7) NULL, 
	[MonthYear] char(10) NULL, 
	[MMYYYY] char(6) NULL, 
	[FirstDayOfMonth] date NULL, 
	[LastDayOfMonth] date NULL, 
	[FirstDayOfQuarter] date NULL, 
	[LastDayOfQuarter] date NULL, 
	[FirstDayOfYear] date NULL, 
	[LastDayOfYear] date NULL, 
	[IsHolidayUSA] bit NULL, 
	[IsWeekday] bit NULL, 
	[HolidayUSA] varchar(50) NULL
);